'use strict'

const randomString = require('../randomString')

const adjectives = [
  'amorphous',
  'amiable',
  'aloof',
  'backtracking',
  'bellicose',
  'bored',
  'crafty',
  'cute',
  'cowardly',
  'ditsy',
  'diligent',
  'delirious',
  'exemplary',
  'energetic',
  'easygoing',
  'faltering',
  'freakish',
  'fanstastical',
  'grouchy',
  'grateful',
  'gregarious',
  'hilarious',
  'hopeful',
  'hammered',
  'illicit',
  'imploding',
  'insidious',
  'jolly',
  'jesting',
  'jarring',
  'kindly',
  'kooky',
  'kaleidoscopic',
  'lame',
  'lazy',
  'lanky',
  'majestic',
  'modest',
  'meek',
  'naughty',
  'nihilistic',
  'nonsensical',
  'opulent',
  'oppressive',
  'outlandish',
  'porous',
  'palatable',
  'prudish',
  'questionable',
  'quick',
  'quarrelsome',
  'rambunctious',
  'rough',
  'ranting',
  'sweet',
  'snarling',
  'saucy',
  'twisted',
  'tardy',
  'telepathic',
  'unctious',
  'unbelievable',
  'unyielding',
  'vexing',
  'vast',
  'voluminous',
  'weary',
  'wandering',
  'wistful',
  'xenodochial',
  'yammering',
  'yodeling',
  'zany',
  'zealous',
  'zippy',
]
const animals = [
  'aardvark',
  'alpaca',
  'albatross',
  'badger',
  'boar',
  'beaver',
  'crocodile',
  'camel',
  'cheetah',
  'deer',
  'duck',
  'donkey',
  'elephant',
  'eagle',
  'emu',
  'falcon',
  'ferret',
  'fox',
  'goose',
  'gecko',
  'gopher',
  'hammerhead',
  'hamster',
  'hummingbird',
  'iguana',
  'impala',
  'indri',
  'jaguar',
  'jackal',
  'jellyfish',
  'kiwi',
  'kangaroo',
  'koala',
  'lemur',
  'lion',
  'llama',
  'macaw',
  'manatee',
  'meerkat',
  'newt',
  'nightingale',
  'octopus',
  'ocelot',
  'otter',
  'peacock',
  'panther',
  'puffin',
  'quail',
  'rabbit',
  'rhinoceros',
  'robin',
  'sloth',
  'salamander',
  'shrimp',
  'tiger',
  'tapir',
  'toucan',
  'vulture',
  'walrus',
  'wallaby',
  'whale',
  'yak',
  'zebra',
]

const random = arr => arr[Math.floor(Math.random() * arr.length)]

const generateId = games => {
  // Fall back to random string ID if there are already more games than possible combos
  const idCount = Object.keys(games).length
  if (idCount >= adjectives.length * animals.length) return randomString(12)

  let newId = `${random(adjectives)}-${random(animals)}`
  while (games[newId]) {
    newId = generateId(games)
  }
  return newId
}

module.exports = generateId
