export default {
  LOG_IN_START: 'ui/logIn/LOG_IN_START',
  LOG_IN_ERROR: 'ui/logIn/LOG_IN_ERROR',
  INVALID_CREDENTIALS: 'ui/logIn/INVALID_CREDENTIALS',
  USERNAME_TAKEN: 'ui/logIn/USERNAME_TAKEN',
  CLEAR_ERRORS: 'ui/logIn/CLEAR_ERRORS',
  RESET: 'ui/logIn/RESET',
}
