export default {
  FETCH_LIST_START: 'ui/list/FETCH_LIST_START',
  FETCH_LIST_SUCCESS: 'ui/list/FETCH_LIST_SUCCESS',
  FETCH_LIST_ERROR: 'ui/list/FETCH_LIST_ERROR',
  CREATE_GAME_START: 'ui/list/CREATE_GAME_START',
  CREATE_GAME_SUCCESS: 'ui/list/CREATE_GAME_SUCCESS',
  CREATE_GAME_ERROR: 'ui/list/CREATE_GAME_ERROR',
  PLAYER_IN_GAME: 'ui/list/PLAYER_IN_GAME',
  CLEAR_ERRORS: 'ui/list/CLEAR_ERRORS',
  RESET: 'ui/list/RESET',
}
